---
influxdb_namespace: databases
# Note: Don't pin old chart versions - Bitnami removes old image tags from Docker Hub
influxdb_chart_version: ""
influxdb_storage_size: "50Gi"
influxdb_hostname: influxdb.homelab.local
influxdb_metrics_enabled: true
