---
pod_network_cidr: "10.10.0.0/16"
service_cidr: "10.96.0.0/12"
cluster_name: "homelab-cluster"

cni_plugin: "calico"

# Calico via Tigera operator (recommended method)
calico_version: "v3.28.0"
tigera_operator_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml"
calico_custom_resources_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml"

kubeconfig_path: /etc/kubernetes/admin.conf
