---
pod_network_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
cluster_name: "homelab-cluster"

cni_plugin: "calico"

calico_version: "v3.31.2"
calico_manifest: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"

kubeconfig_path: /etc/kubernetes/admin.conf
