---
prometheus_namespace: monitoring
prometheus_stack_version: "68.4.5"

# grafana_admin_password must be set in group_vars/all.yml or via vault
prometheus_retention: "15d"
prometheus_storage_size: "50Gi"
