all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            kluster1:
              ansible_host: 192.168.1.21
        workers:
          hosts:
            kluster2:
              ansible_host: 192.168.1.22
            kluster3:
              ansible_host: 192.168.1.23
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
